%YAML:1.0
---
model_type: PINHOLE
camera_name: stereo_camera_right
image_width: 640
image_height: 360
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   gamma1: 555.6653734913782
   gamma2: 555.6653734913782
   u0: 320.5
   v0: 180.5